apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcg
  labels:
    app: catalog-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMq__Host: "rabbitmq"
  MongoDbSettings__DatabaseName: "catalogdb"
  JwtSettings__Issuer: "FiapCloudGames"
  JwtSettings__Audience: "FiapCloudGames"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  namespace: fcg
  labels:
    app: catalog-api
type: Opaque
stringData:
  MongoDbSettings__ConnectionString: "mongodb://mongodb:27017"
  # IMPORTANTE: idêntica à do users-api-secret (valida o JWT emitido por ele).
  JwtSettings__SecretKey: "FiapCloudGames_Demo_SecretKey_Com_Pelo_Menos_256_Bits_Para_HMAC_SHA256!"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: fcg
  labels:
    app: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: catalog-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: catalog-api-config
            - secretRef:
                name: catalog-api-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: fcg
  labels:
    app: catalog-api
spec:
  type: ClusterIP
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 8080
